# Generated by Django 5.2.1 on 2025-10-22 14:59

import booking.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-date", "-time", "-id"]},
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(validators=[booking.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("user", "date", "time"), name="uniq_user_date_time"
            ),
        ),
    ]
